# -*- coding: utf-8 -*-
"""Implementación Modelo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8lPdIVuM2YuW60lrfoiuzgQ2HtSs6x9

# Implementación del Modelo

Se genera nuevos ejemplos para probar el funcionamiento del modelo y determinar si hay fraude o no en una transacción.
"""

import joblib

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Load the dataset to define 'df'
df = pd.read_csv('/content/creditcard.csv')
X = df.drop(['Class', 'Time'], axis=1)
y = df['Class']

import numpy as np

# Ruta donde guardaste el modelo en Google Drive
model_filename = '/content/drive/MyDrive/fraud_detection_model_optuna_calibrated_v3.joblib'

# Cargar el modelo
try:
    loaded_model = joblib.load(model_filename)
    print(f"Modelo '{model_filename}' cargado exitosamente.")
except FileNotFoundError:
    print(f"Error: El archivo '{model_filename}' no fue encontrado. Verifica la ruta.")
    loaded_model = None

if loaded_model:
    print("\n--- Generando predicciones con nuevos datos sintéticos ---")

    feature_columns = X.columns.tolist()

    # Generar 5 ejemplos de datos sintéticos
    # Para simplificar, generamos valores aleatorios basados en la media y desviación estándar
    # de cada característica en el DataFrame original.
    # En un escenario real, estos datos podrían venir de transacciones en vivo.
    num_new_examples = 5
    new_data_dict = {}
    for col in feature_columns:
        mean_val = df[col].mean()
        std_val = df[col].std()
        # Generamos valores aleatorios alrededor de la media con cierta dispersión
        new_data_dict[col] = np.random.normal(mean_val, std_val * 0.5, num_new_examples)

    sample_new_data = pd.DataFrame(new_data_dict, columns=feature_columns)

    print("Ejemplos de 'nuevos datos' sintéticos generados:")

    # Realizar predicciones para cada ejemplo sintético
    for i in range(len(sample_new_data)):
        single_example = sample_new_data.iloc[[i]]
        prediction = loaded_model.predict(single_example)
        prediction_proba = loaded_model.predict_proba(single_example)

        print(f"\n--- Ejemplo Sintético {i+1} ---")
        print(single_example)
        print(f"Predicción de la clase: {prediction[0]} (0: No Fraude, 1: Fraude)")
        print(f"Probabilidad de No Fraude: {prediction_proba[0][0]:.4f}")
        print(f"Probabilidad de Fraude: {prediction_proba[0][1]:.4f}")
else:
    print("No se pudo cargar el modelo. Verifica la ruta y que el archivo exista.")

import numpy as np

# Ruta donde guardaste el modelo en Google Drive
model_filename = '/content/drive/MyDrive/fraud_detection_model_optuna_calibrated_v3.joblib'

# Cargar el modelo
try:
    loaded_model = joblib.load(model_filename)
    print(f"Modelo '{model_filename}' cargado exitosamente.")
except FileNotFoundError:
    print(f"Error: El archivo '{model_filename}' no fue encontrado. Verifica la ruta.")
    loaded_model = None

if loaded_model:
    print("\n--- Generando predicciones con nuevos datos sintéticos ---")

    feature_columns = X.columns.tolist()

    num_non_fraud_examples = 3
    num_fraud_examples = 2

    synthetic_data_list = []

    # Separar el DataFrame original por clase para obtener estadísticas
    df_fraud = df[df['Class'] == 1]
    df_non_fraud = df[df['Class'] == 0]

    # Generar ejemplos sintéticos de NO FRAUDES
    for _ in range(num_non_fraud_examples):
        new_row_dict = {}
        for col in feature_columns:
            mean_val = df_non_fraud[col].mean()
            std_val = df_non_fraud[col].std()
            # Generamos valores aleatorios alrededor de la media de transacciones no fraudulentas
            new_row_dict[col] = np.random.normal(mean_val, std_val * 0.5) # Usamos 0.5*std para mantenerlos 'cerca' de la media
        synthetic_data_list.append(new_row_dict)

    # Generar ejemplos sintéticos de FRAUDE
    for _ in range(num_fraud_examples):
        new_row_dict = {}
        for col in feature_columns:
            mean_val = df_fraud[col].mean()
            std_val = df_fraud[col].std()
            new_row_dict[col] = np.random.normal(mean_val, std_val * 1.0)
        synthetic_data_list.append(new_row_dict)

    # Crear un DataFrame con todos los ejemplos sintéticos
    sample_new_data = pd.DataFrame(synthetic_data_list, columns=feature_columns)

    print("Ejemplos de 'nuevos datos' sintéticos generados:")

    # Realizar predicciones para cada ejemplo sintético
    for i in range(len(sample_new_data)):
        single_example = sample_new_data.iloc[[i]]
        prediction = loaded_model.predict(single_example)
        prediction_proba = loaded_model.predict_proba(single_example)

        print(f"\n--- Ejemplo Sintético {i+1} ---")
        print(single_example)
        print(f"Predicción de la clase: {prediction[0]} (0: No Fraude, 1: Fraude)")
        print(f"Probabilidad de No Fraude: {prediction_proba[0][0]:.4f}")
        print(f"Probabilidad de Fraude: {prediction_proba[0][1]:.4f}")
else:
    print("No se pudo cargar el modelo. Verifica la ruta y que el archivo exista.")